### PR TITLE
Various patches

### PR DESCRIPTION
**Pull request by neeshy**
Minor changes/bugfixes:
f5d4780 `Combine multiple SQL statements into one`
cf4e980 `Re-use local variable in handle_xbrefs`
8ceb7c0 `Always link to /<board>/<parent>#<number>`
b5b4eaf `Avoid potential id collision when generating recent page`
f1580e8 `Make all posts look consistent in recent view`
4662f5c `Add a thread indicator to posts on the recent page`
dae21d5 `Parent should already be a number`
f7bab2e `Fix bug related to url parsing`
b23cf6c `Read error and no need for ternary`
8a0fb33 `Use pico.board.exists instead of rewriting SQL query`
9a21cd1 `Redirect to mod panel when logged in`
9678349 `Prefer spaces to tabs`

Major changes:
460f44e `Remove URI prefix`
f69edc1 `Titlecase media and static to avoid collision with board names`
864c95f `Re-implement OpenBSD pledge/unveil support`
a38dad1 `SQLite3 micro-optimizations`
06a8d0c `Use dispatcher instead of a large if/else statement`
9606d86 `Fix indentation in handler functions`
d240e07 `Implement overboard index`
3feb84e `Fix URI patterns for board names`

### CODE REVIEW

**Comment by neeshy** [comment]
I've included most of the patches I have. Let me know which commits you want/don't want and I'll do a rebase.

**Comment by neeshy** [comment]
BTW, for https://github.com/vxiiduu/picochan/commit/74559c5d14f7810dc2290365fc5a43e341ffd5ce this is the nginx configuration I use:
```
root /var/www/picochan/$server_name;

location /Media {
}
location /Static {
}
location / {
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root/pico;
    fastcgi_param PATH_INFO $uri;
    fastcgi_param QUERY_STRING $args;
    fastcgi_param HTTP_HOST $server_name;
    fastcgi_pass unix:/var/www/run/$server_name.sock;
}
```

**Comment by vxiiduu** [comment]
I haven't looked at the rest but commit f5d4780 is broken. If you upload multiple of the same file, it only shows up once.

**Comment by neeshy** [comment]
> I haven't looked at the rest but commit [f5d4780](https://github.com/vxiiduu/picochan/commit/f5d478012678cd745245fb548e134c60bbca70a0) is broken. If you upload multiple of the same file, it only shows up once.

I've tested this and found that this isn't the case. I'm using JOINs in instead of sub-queries. The former retains duplicate rows while the latter does not.

**Comment by vxiiduu** [comment]
True. I didn't remember correctly and I thought I already tried this in the past (I did, but with subqueries as you said). I'll start incorporating these changes

**Comment by hawkoon** [comment]
Don't know why there isn't an 'Issues' page available so I'll ask here:
Could you make picochan easier to install? For example on a Debian installation? The current installation instructions confuse me.

**Comment by vxiiduu** [comment]
I've incorporated everything I want from this pull request so I will now close it.
Thanks for the contributions.
@hawkoon Issues are to be asked on nanochan or to my email/discord. I don't check github often.

**Pull request closed without merging**
